"""Add TireSet model with current_mileage tracking

Revision ID: 9b600cf99ad0
Revises: 
Create Date: 2026-02-13 04:46:36.186274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b600cf99ad0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tire_set_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tire_sets', ['tire_set_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_components', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tire_set_id')

    # ### end Alembic commands ###
