"""Add tire set mileage tracking fields

Revision ID: add_tire_set_mileage_tracking
Revises: 9b600cf99ad0
Create Date: 2026-02-12

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_tire_set_mileage_tracking'
down_revision = '9b600cf99ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new columns to tire_sets table
    with op.batch_alter_table('tire_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accumulated_mileage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mileage_at_last_swap', sa.Integer(), nullable=True))

    # Set defaults for existing rows
    op.execute("UPDATE tire_sets SET accumulated_mileage = 0 WHERE accumulated_mileage IS NULL")

    # For existing sets that are "current" (have active components), set mileage_at_last_swap to install_mileage
    op.execute("""
        UPDATE tire_sets
        SET mileage_at_last_swap = tire_sets.install_mileage
        WHERE EXISTS (
            SELECT 1 FROM vehicle_components
            WHERE vehicle_components.tire_set_id = tire_sets.id
            AND vehicle_components.is_active = true
        )
    """)

    # Make accumulated_mileage non-nullable with default
    with op.batch_alter_table('tire_sets', schema=None) as batch_op:
        batch_op.alter_column('accumulated_mileage', nullable=False, server_default='0')

    # Remove old current_mileage column (rename it first to avoid conflicts, then drop)
    with op.batch_alter_table('tire_sets', schema=None) as batch_op:
        batch_op.drop_column('current_mileage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Restore old current_mileage column
    with op.batch_alter_table('tire_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_mileage', sa.Integer(), nullable=True))

    # Drop new columns
    with op.batch_alter_table('tire_sets', schema=None) as batch_op:
        batch_op.drop_column('mileage_at_last_swap')
        batch_op.drop_column('accumulated_mileage')

    # ### end Alembic commands ###
